require("options")
require("keymaps")
require("plugins.lazy")
require("plugins.keymaps")
require("plugins.options")
require('plugins.lsp')
-- require('plugins.lualine')
-- require('plugins.treesitter')
